// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoryByProofLoaderController from "./category_by_proof_loader_controller"
application.register("category-by-proof-loader", CategoryByProofLoaderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NestedRondoController from "./nested_rondo_controller"
application.register("nested-rondo", NestedRondoController)

import SwimmerLoaderController from "./swimmer_loader_controller"
application.register("swimmer-loader", SwimmerLoaderController)
